# Generated by Django 5.2.3 on 2025-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('calories', models.IntegerField()),
                ('foodPicture', models.ImageField(upload_to='images/')),
                ('objectiveType', models.CharField(choices=[('WL', 'Weight Lose'), ('BB', 'Body Building'), ('FG', 'Fitness Gain')], max_length=5)),
                ('kind', models.CharField(choices=[('VG', 'Vegetarian'), ('NVG', 'Non - Vegetarian')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('totalCalories', models.IntegerField()),
                ('recipeImage', models.ImageField(upload_to='images/')),
                ('kind', models.CharField(choices=[('VG', 'Vegetarian'), ('NVG', 'Non - Vegetarian')], max_length=5)),
                ('objectiveType', models.CharField(choices=[('WL', 'Weight Lose'), ('BB', 'Body Building'), ('FG', 'Fitness Gain')], max_length=5)),
            ],
        ),
    ]
