# Generated by Django 5.2.3 on 2025-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0002_alter_fooditem_benefits_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='foodPicture',
            field=models.ImageField(upload_to='images/foods/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='kind',
            field=models.CharField(choices=[('VG', 'Vegetarian'), ('NVG', 'Non - Vegetarian')], default='VG', max_length=5),
        ),
    ]
