# Generated by Django 5.2.3 on 2025-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0003_alter_fooditem_foodpicture_alter_fooditem_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(upload_to='images/recipes/'),
        ),
    ]
