# Generated by Django 5.2.3 on 2025-06-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectiveType', models.CharField(choices=[('WL', 'Weight Lose'), ('BB', 'Body Building'), ('FG', 'Fitness Gain')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('duration_in_days', models.IntegerField(default=7)),
                ('completion_count', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField()),
                ('completion_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPerDayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('exercises', models.ManyToManyField(to='exercises.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GeneratedPerDayPlans', to='plans.plan')),
            ],
        ),
    ]
