# Generated by Django 5.2.3 on 2025-06-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedperdayplan',
            name='day_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
