# Generated by Django 5.2.3 on 2025-06-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_generatedperdayplan_day_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='completion_status',
        ),
    ]
