# Generated by Django 5.2.3 on 2025-06-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_completion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedperdayplan',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
