# Generated by Django 5.2.3 on 2025-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('toughnessLevel', models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], max_length=4)),
                ('objectiveType', models.CharField(choices=[('WL', 'Weight Lose'), ('BB', 'Body Building'), ('FG', 'Fitness Gain')], max_length=5)),
                ('giphy', models.ImageField(upload_to='giphys/')),
            ],
        ),
    ]
