# Generated by Django 5.2.3 on 2025-06-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_of_customer', to='exercises.exercise')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='exercises.exercise')),
            ],
        ),
    ]
